local colors = {
    bg = "#1E1F22",
    fg = "#A9B7C6",
    black = "#222326",
    bright_black = "#3C3F41",
    white = "#A9B7C6",
    comments = "#808080",
    red = "#FF6B68",
    bright_red = "#FF6B68",  -- You may adjust this if needed
    pale_red = "#F5B3B3",  -- New pale red
    green = "#99CC99",
    bright_green = "#99CC99",
    teal = "#2FBAA3",
    pale_yellow = "#F4D080",  -- Adjusted pale yellow
    yellow = "#FFD866",
    dark_yellow = "#D4A630",
    pale_blue = "#9EBBD9",
    blue = "#6A9CD1",            -- Original blue
    bright_blue = "#8AB2E6",     -- Lighter blue for bright_blue
    cyan = "#78DCE8",
    bright_cyan = "#78DCE8",
    magenta = "#C792EA",
    bright_magenta = "#C792EA",
    bright_white = "#FFFFFF",
    pale_orange = "#CF8E6D",
    orange = "#E07A5F",
    bright_orange = "#FF8A6A",
}

local theme = {
    -- UI elements
    Normal = { fg = colors.fg, bg = colors.bg },
    Comment = { fg = colors.comments },
    CursorLine = { bg = colors.black },
    CursorColumn = { bg = colors.black },
    Visual = { bg = colors.bright_black },
    LineNr = { fg = colors.bright_black },
    CursorLineNr = { fg = colors.white },
    StatusLine = { fg = colors.white, bg = colors.black },
    StatusLineNC = { fg = colors.bright_black, bg = colors.black },
    VertSplit = { fg = colors.black, bg = colors.black },
    MatchParen = { fg = colors.yellow, bold = true },
    Pmenu = { fg = colors.white, bg = colors.black },
    PmenuSel = { fg = colors.black, bg = colors.blue },
    PmenuSbar = { bg = colors.bright_black },
    PmenuThumb = { bg = colors.blue },

    -- Float-specific highlights
    NormalFloat = { fg = colors.fg, bg = colors.bg }, -- Ensure the background is consistent with Normal
    FloatBorder = { fg = colors.bright_black, bg = colors.bg }, -- Border color for floating windows

    -- Syntax groups
    Constant = { fg = colors.red },
    String = { fg = colors.green },
    Character = { fg = colors.green },
    Number = { fg = colors.orange },
    Boolean = { fg = colors.magenta },
    Float = { fg = colors.orange },
    Identifier = { fg = colors.pale_blue },
    Statement = { fg = colors.orange },
    Conditional = { fg = colors.orange },
    Repeat = { fg = colors.orange },
    Label = { fg = colors.orange },
    Operator = { fg = colors.fg },
    Keyword = { fg = colors.bright_orange },
    Exception = { fg = colors.red },
    PreProc = { fg = colors.orange },
    Include = { fg = colors.blue },
    Define = { fg = colors.orange },
    Macro = { fg = colors.orange },
    PreCondit = { fg = colors.orange },
    Type = { fg = colors.yellow },
    StorageClass = { fg = colors.yellow },
    Structure = { fg = colors.teal },
    Typedef = { fg = colors.yellow },
    Special = { fg = colors.red },
    SpecialChar = { fg = colors.blue },
    Tag = { fg = colors.orange },
    Delimiter = { fg = colors.fg },
    SpecialComment = { fg = colors.bright_black, italic = true },
    Debug = { fg = colors.red },
    Underlined = { fg = colors.blue, underline = true },
    Ignore = { fg = colors.bright_black },
    Error = { fg = colors.red, bg = colors.bg, bold = true },
    Todo = { fg = colors.yellow, bg = colors.bg, bold = true },
    Function = { fg = colors.bright_blue, underline = true },
    goBuiltins = { fg = colors.bright_blue, underline = true },
    goFunctionCall = { fg = colors.bright_blue, underline = true },
    goBuiltins = { link = "Function" },

    -- Treesitter-specific highlights
    TSProperty = { fg = colors.pale_blue },
    TSAnnotation = { fg = colors.yellow },
    TSAttribute = { fg = colors.yellow },
    TSBoolean = { fg = colors.magenta },
    TSCharacter = { fg = colors.green },
    TSComment = { fg = colors.bright_black, italic = true },
    TSConditional = { fg = colors.orange },
    TSConstant = { fg = colors.red },
    TSConstBuiltin = { fg = colors.cyan },
    TSConstMacro = { fg = colors.cyan },
    TSConstructor = { fg = colors.blue },
    TSEmphasis = { fg = colors.white, italic = true },
    TSError = { fg = colors.red },
    TSException = { fg = colors.red },
    TSField = { fg = colors.blue },
    TSFloat = { fg = colors.cyan },
    TSFunction = { fg = colors.bright_blue, underline = true },
    TSFuncBuiltin = { fg = colors.bright_blue, underline = true },
    TSFuncMacro = { fg = colors.orange },
    TSInclude = { fg = colors.blue },
    TSKeyword = { fg = colors.keyword },
    TSKeywordFunction = { fg = colors.orange },
    TSKeywordOperator = { fg = colors.orange },
    TSKeywordReturn = { fg = colors.orange },
    TSLabel = { fg = colors.orange },
    TSMethod = { fg = colors.bright_blue, underline = true },
    TSNamespace = { fg = colors.orange },
    TSNone = { fg = colors.fg },
    TSNumber = { fg = colors.orange },
    TSOperator = { fg = colors.fg },
    TSParameter = { fg = colors.blue },
    TSParameterReference = { fg = colors.blue },
    TSPunctDelimiter = { fg = colors.fg },
    TSPunctBracket = { fg = colors.fg },
    TSPunctSpecial = { fg = colors.fg },
    TSRepeat = { fg = colors.orange },
    TSString = { fg = colors.green },
    TSStringRegex = { fg = colors.green },
    TSStringEscape = { fg = colors.blue },
    TSTag = { fg = colors.orange },
    TSTagDelimiter = { fg = colors.fg },
    TSText = { fg = colors.fg },
    TSStrong = { fg = colors.white, bold = true },
    TSUnderline = { fg = colors.blue, underline = true },
    TSType = { fg = colors.yellow },
    TSTypeBuiltin = { fg = colors.yellow },
    TSVariable = { fg = colors.blue },
    TSVariableBuiltin = { fg = colors.blue },

    -- Highlight group for the specific 'teal' keyword in package declarations
    ["@function"] = { fg = colors.bright_blue, underline = true },
    ["@function.builtin"] = { fg = colors.bright_blue, underline = true },
    ["@method"] = { fg = colors.bright_blue, underline = true },
}

return theme
