local colors = {
    bg = "#1E1F22",
    fg = "#C3CDD7",  -- 30% lighter than the original "#A9B7C6"
    black = "#222326",
    dark_black = "#000000",
    bright_black = "#3C3F41",
    white = "#A9B7C6",
    grey = "#808080",
    red = "#FF6B68",
    bright_red = "#FF6B68",  -- You may adjust this if needed
    pale_red = "#F5B3B3",  -- New pale red
    green = "#99CC99",
    bright_green = "#99CC99",
    teal = "#2FBAA3",
    pale_yellow = "#F4D080",  -- Adjusted pale yellow
    yellow = "#FFD866",
    dark_yellow = "#D4A630",
    pale_blue = "#9EBBD9",
    blue = "#66A6FF",            -- Original blue
    bright_blue = "#8AB2E6",     -- Lighter blue for bright_blue
    cyan = "#78DCE8",
    bright_cyan = "#78DCE8",
    magenta = "#C792EA",
    bright_magenta = "#C792EA",
    bright_white = "#FFFFFF",
    pale_orange = "#CF8E6D",
    orange = "#E07A5F",
    bright_orange = "#FF8A6A",
}

local theme = {
    -- UI elements
    Normal = { fg = colors.fg, bg = colors.bg },
    Comment = { fg = colors.grey },
    CursorLine = { bg = colors.black },
    CursorColumn = { bg = colors.black },
    Visual = { bg = colors.bright_black },
    LineNr = { fg = colors.bright_black },
    CursorLineNr = { fg = colors.white },
    StatusLine = { fg = colors.white, bg = colors.black },
    StatusLineNC = { fg = colors.bright_black, bg = colors.black },
    VertSplit = { fg = colors.black, bg = colors.black },
    MatchParen = { fg = colors.yellow, bold = true },
    Pmenu = { fg = colors.white, bg = colors.black },
    PmenuSel = { fg = colors.black, bg = colors.blue },
    PmenuSbar = { bg = colors.bright_black },
    PmenuThumb = { bg = colors.blue },
    NormalFloat = { fg = colors.fg, bg = colors.bg },
    FloatBorder = { fg = colors.bright_black, bg = colors.bg },

    -- General syntax groups
    Constant = { fg = colors.red },
    String = { fg = colors.green },
    Comment = { fg = colors.bright_black, italic = true },
    Identifier = { fg = colors.pale_blue },
    Function = { fg = colors.bright_blue },
    Keyword = { fg = colors.bright_orange },
    Operator = { fg = colors.fg },
    Type = { fg = colors.teal },
    Special = { fg = colors.red },
    Underlined = { fg = colors.blue, underline = true },
    Error = { fg = colors.red, bg = colors.bg, bold = true },
    Todo = { fg = colors.yellow, bg = colors.bg, bold = true },

    -- Treesitter groups 
    ["@annotation"] = { fg = colors.yellow },
    ["@attribute"] = { fg = colors.yellow },
    ["@boolean"] = { fg = colors.magenta },
    ["@character"] = { fg = colors.green },
    ["@comment"] = { fg = colors.grey, italic = true },
    ["@conditional"] = { fg = colors.orange },
    ["@constant"] = { fg = colors.red },
    ["@constant.builtin"] = { fg = colors.red },
    ["@constant.macro"] = { fg = colors.cyan },
    ["@constructor"] = { fg = colors.blue },
    ["@error"] = { fg = colors.red },
    ["@exception"] = { fg = colors.red },
    ["@field"] = { fg = colors.blue },
    ["@float"] = { fg = colors.cyan },
    ["@function"] = { fg = colors.blue },
        ["@function.builtin"] = { fg = colors.blue },
            ["@function.builtin.go"] = { fg = colors.blue },
                ["@function.call.go"] = { fg = colors.blue },
                    ["@function.macro"] = { fg = colors.orange },
                        ["@include"] = { fg = colors.blue },
                        ["@keyword"] = { fg = colors.pale_orange },
                        ["@keyword.function"] = { fg = colors.black, bg = colors.orange, bold = true },
                            ["@keyword.operator"] = { fg = colors.orange },
                            ["@keyword.return"] = { fg = colors.orange, italic = true },
                           ["@keyword.type"] = { fg = colors.black, bg = colors.teal, bold = true }, 
                            ["@label"] = { fg = colors.orange },
                            ["@method"] = { fg = colors.bright_blue, underline = true },
                            ["@namespace"] = { fg = colors.orange },
                            ["@number"] = { fg = colors.orange },
                            ["@operator"] = { fg = colors.fg },
                            ["@parameter"] = { fg = colors.blue },
                            -- ["@property"] = { fg = colors.blue },
                            ["@punctuation.bracket"] = { fg = colors.cyan, bold = true },
                            ["@punctuation.delimiter"] = { fg = colors.fg },
                            ["@punctuation.special"] = { fg = colors.fg },
                            ["@repeat"] = { fg = colors.orange },
                                ["@string"] = { fg = colors.green },
                                ["@string.escape"] = { fg = colors.blue },
                                ["@string.regex"] = { fg = colors.green },
                                ["@tag"] = { fg = colors.orange },
                                ["@tag.delimiter"] = { fg = colors.fg },
                                ["@text"] = { fg = colors.fg },
                                ["@text.strong"] = { fg = colors.white, bold = true },
                                ["@text.emphasis"] = { fg = colors.white, italic = true },
                                ["@text.underline"] = { fg = colors.blue, underline = true },
                                ["@type"] = { fg = colors.teal },
                                ["@type.builtin"] = { fg = colors.teal },
                                ["@variable"] = { fg = colors.fg },
                                ["@variable.builtin"] = { fg = colors.fg, bold = true },
                                ["@property"] = { fg = colors.pale_red },
                                
    -- Additional groups to ensure comprehensive coverage
    ["@debug"] = { fg = colors.red },
    ["@define"] = { fg = colors.orange },
    ["@method.call"] = { fg = colors.bright_blue },
    ["@none"] = { fg = colors.fg },
    ["@parameter.reference"] = { fg = colors.blue },
    ["@preproc"] = { fg = colors.orange },
    ["@storageclass"] = { fg = colors.yellow },
    ["@string.special"] = { fg = colors.blue },
    ["@symbol"] = { fg = colors.pale_blue },
    ["@tag.attribute"] = { fg = colors.yellow },
    ["@text.danger"] = { fg = colors.red, bold = true },
    ["@text.environment"] = { fg = colors.yellow },
    ["@text.environment.name"] = { fg = colors.yellow, bold = true },
    ["@text.literal"] = { fg = colors.green },
    ["@text.math"] = { fg = colors.blue },
    ["@text.note"] = { fg = colors.bright_black, bold = true },
    ["@text.reference"] = { fg = colors.blue, underline = true },
    ["@text.strike"] = { fg = colors.fg, strikethrough = true },
    ["@text.title"] = { fg = colors.yellow, bold = true },
    ["@text.uri"] = { fg = colors.blue, underline = true },
    ["@text.warning"] = { fg = colors.yellow, bold = true },
    ["@todo"] = { fg = colors.yellow, bold = true },
    ["@type.definition"] = { fg = colors.yellow },
    ["@type.qualifier"] = { fg = colors.teal },

    ["@field.go"] = { fg = colors.blue },  -- specifically for Go struct fields
}

return theme
