local colors = {
    bg = "#1E1F22",
    fg = "#A9B7C6",
    black = "#2B2B2B",
    red = "#FF6B68",
    green = "#99CC99",
    yellow = "#FFD866",
    blue = "#6A9CD1",
    magenta = "#C792EA",
    cyan = "#78DCE8",
    white = "#A9B7C6",
    bright_black = "#3C3F41",
    bright_red = "#FF6B68",
    bright_green = "#99CC99",
    bright_yellow = "#FFD866",
    bright_blue = "#6A9CD1",
    bright_magenta = "#C792EA",
    bright_cyan = "#78DCE8",
    bright_white = "#FFFFFF",
    keyword = "#CF8E6D",  -- General keyword color
    main = "#2FBAA3",     -- Specific color for 'main' keyword in package
    orange ="#E07A5F",
    comments = "#808080"
}

local theme = {
    -- UI elements
    Normal = { fg = colors.fg, bg = colors.bg },
    Comment = { fg = colors.comments, italic = true },
    CursorLine = { bg = colors.black },
    CursorColumn = { bg = colors.black },
    Visual = { bg = colors.bright_black },
    LineNr = { fg = colors.bright_black },
    CursorLineNr = { fg = colors.white },
    StatusLine = { fg = colors.white, bg = colors.black },
    StatusLineNC = { fg = colors.bright_black, bg = colors.black },
    VertSplit = { fg = colors.black, bg = colors.black },
    MatchParen = { fg = colors.yellow, bold = true },
    Pmenu = { fg = colors.white, bg = colors.black },
    PmenuSel = { fg = colors.black, bg = colors.blue },
    PmenuSbar = { bg = colors.bright_black },
    PmenuThumb = { bg = colors.blue },

    -- Syntax groups
    Constant = { fg = colors.cyan },
    String = { fg = colors.green },
    Character = { fg = colors.green },
    Number = { fg = colors.orange },
    Boolean = { fg = colors.magenta },
    Float = { fg = colors.orange},
    Identifier = { fg = colors.cyan },
    Function = { fg = colors.blue, bold = true },
    Statement = { fg = colors.keyword },
    Conditional = { fg = colors.keyword },
    Repeat = { fg = colors.keyword },
    Label = { fg = colors.keyword },
    Operator = { fg = colors.fg },
    Keyword = { fg = colors.keyword },  -- General keyword color
    Exception = { fg = colors.red },
    PreProc = { fg = colors.keyword },
    Include = { fg = colors.blue }, -- e.g., #include in C/C++
    Define = { fg = colors.keyword }, -- e.g., #define in C/C++
    Macro = { fg = colors.keyword },
    PreCondit = { fg = colors.keyword }, -- e.g., #if, #else
    Type = { fg = colors.yellow },
    StorageClass = { fg = colors.yellow },
    Structure = { fg = colors.main },
    Typedef = { fg = colors.yellow },
    Special = { fg = colors.blue },
    SpecialChar = { fg = colors.blue },
    Tag = { fg = colors.keyword }, -- e.g., XML tags
    Delimiter = { fg = colors.fg }, -- e.g., brackets and punctuation
    SpecialComment = { fg = colors.bright_black, italic = true },
    Debug = { fg = colors.red },
    Underlined = { fg = colors.blue, underline = true },
    Ignore = { fg = colors.bright_black },
    Error = { fg = colors.red, bg = colors.bg, bold = true },
    Todo = { fg = colors.yellow, bg = colors.bg, bold = true },

    -- Treesitter-specific highlights
    TSAnnotation = { fg = colors.yellow },
    TSAttribute = { fg = colors.yellow },
    TSBoolean = { fg = colors.cyan },
    TSCharacter = { fg = colors.green },
    TSComment = { fg = colors.bright_black, italic = true },
    TSConditional = { fg = colors.keyword },
    TSConstant = { fg = colors.cyan },
    TSConstBuiltin = { fg = colors.cyan },
    TSConstMacro = { fg = colors.cyan },
    TSConstructor = { fg = colors.blue },
    TSEmphasis = { fg = colors.white, italic = true },
    TSError = { fg = colors.red },
    TSException = { fg = colors.red },
    TSField = { fg = colors.blue },
    TSFloat = { fg = colors.cyan },
    TSFunction = { fg = colors.blue },
    TSFuncBuiltin = { fg = colors.blue },
    TSFuncMacro = { fg = colors.keyword },
    TSInclude = { fg = colors.blue },
    TSKeyword = { fg = colors.keyword },  -- General keyword color
    TSKeywordFunction = { fg = colors.keyword },
    TSKeywordOperator = { fg = colors.keyword },
    TSKeywordReturn = { fg = colors.keyword },
    TSLabel = { fg = colors.keyword },
    TSMethod = { fg = colors.blue },
    TSNamespace = { fg = colors.keyword },
    TSNone = { fg = colors.fg },
    TSNumber = { fg = colors.orange },
    TSOperator = { fg = colors.fg },
    TSParameter = { fg = colors.blue },
    TSParameterReference = { fg = colors.blue },
    TSProperty = { fg = colors.cyan },
    TSPunctDelimiter = { fg = colors.fg },
    TSPunctBracket = { fg = colors.fg },
    TSPunctSpecial = { fg = colors.fg },
    TSRepeat = { fg = colors.keyword },
    TSString = { fg = colors.green },
    TSStringRegex = { fg = colors.green },
    TSStringEscape = { fg = colors.blue },
    TSSymbol = { fg = colors.blue },
    TSTag = { fg = colors.keyword },
    TSTagDelimiter = { fg = colors.fg },
    TSText = { fg = colors.fg },
    TSStrong = { fg = colors.white, bold = true },
    TSUnderline = { fg = colors.blue, underline = true },
    TSType = { fg = colors.yellow },
    TSTypeBuiltin = { fg = colors.yellow },
    TSVariable = { fg = colors.blue },
    TSVariableBuiltin = { fg = colors.blue },

    -- Highlight group for the specific 'main' keyword in package declarations
    GoPackageMain = { fg = colors.main },  -- Custom highlight group for `main` in `package main`
}

return theme
