unbind r
bind r source-file ~/.config/tmux/tmux.conf

# Fix themes in neovim
set-option -sa terminal-overrides ",xterm*:Tc"
# Fix themes in helix
set -g default-terminal "xterm-256color"

# reset leader
set -g prefix C-s

# fix delay on escape key in neovim / helix
set -sg escape-time 10

# Enable mouse support for pane resizing
set -g mouse on

# vim/helix pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# tmux bar at top
set-option -g status-position top

# Plugins
set -g @plugin 'tmux-plugins/tpm'
#set -g @plugin 'catppuccin/tmux'
set -g @plugin 'khanghh/tmux-dark-plus-theme'
run '~/.config/tmux/plugins/tpm/tpm'

#Configure cattpuccin tmux theme
# set -g @catppuccin_window_left_separator ""
# set -g @catppuccin_window_right_separator " "
# set -g @catppuccin_window_middle_separator " █"
# set -g @catppuccin_window_number_position "right"

# set -g @catppuccin_window_default_fill "number"
# set -g @catppuccin_window_default_text "#W"

# set -g @catppuccin_window_current_fill "number"
# set -g @catppuccin_window_current_text "#W"

# set -g @catppuccin_status_modules_right "directory user host session"
# set -g @catppuccin_status_left_separator  " "
# set -g @catppuccin_status_right_separator ""
# set -g @catppuccin_status_fill "icon"
# set -g @catppuccin_status_connect_separator "no"

# set -g @catppuccin_directory_text "#{pane_current_path}"
